# Version is now obsolete. This compose configuration assumes version 3.8.

x-logging: &logging
    logging:
        driver: 'json-file'
        options:
            max-file: '10'
            max-size: '1gb'

networks:
    orientation:
        driver: bridge

services:
    migrations:
        build:
            context: ./prisma
            dockerfile: Dockerfile
        container_name: migrations
        tty: true
        depends_on:
            postgres:
                condition: service_healthy
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - /etc/timezone:/etc/timezone:ro
        environment:
            - DATABASE_URL=postgresql://orientation:${POSTGRES_PASSWORD}@postgres:5432
        networks:
            - orientation
        <<: *logging

    orientation_app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: orientation-app
        restart: unless-stopped
        stop_signal: SIGINT
        stop_grace_period: 5m
        tty: true
        depends_on:
            postgres:
                condition: service_healthy
            redis_ephemeral:
                condition: service_healthy
            redis_persistent:
                condition: service_healthy
            migrations:
                condition: service_completed_successfully
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - /etc/timezone:/etc/timezone:ro
        ports:
            - 0.0.0.0:3001:3000
        env_file:
            - .env
        environment:
            - DATABASE_URL=postgresql://orientation:${POSTGRES_PASSWORD}@postgres:5432
        networks:
            - orientation
        <<: *logging

    postgres:
        image: postgres:latest
        container_name: postgres
        pull_policy: always
        restart: unless-stopped
        stop_signal: SIGINT
        stop_grace_period: 5m
        tty: true
        shm_size: 256mb
        healthcheck:
            test: ['CMD-SHELL', 'pg_isready']
            interval: 60s
            timeout: 5s
            retries: 5
            start_period: 40s
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - /etc/timezone:/etc/timezone:ro
            - ./db:/var/lib/postgresql/data:rw
        ports:
            - 127.0.0.1:5432:5432
        environment:
            - POSTGRES_USER=orientation
        env_file:
            - .env
        networks:
            - orientation
        <<: *logging

    redis_ephemeral:
        image: redis:latest
        container_name: redis-ephemeral
        pull_policy: always
        restart: unless-stopped
        stop_signal: SIGINT
        stop_grace_period: 5m
        tty: true
        healthcheck:
            test: ['CMD', 'redis-cli', 'ping']
            interval: 60s
            timeout: 5s
            retries: 3
            start_period: 40s
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - /etc/timezone:/etc/timezone:ro
        ports:
            - 127.0.0.1:6379:6379
        networks:
            - orientation
        <<: *logging

    redis_persistent:
        image: redis:latest
        container_name: redis_persistent
        command: redis-server --appendonly yes
        pull_policy: always
        restart: unless-stopped
        stop_signal: SIGINT
        stop_grace_period: 5m
        tty: true
        healthcheck:
            test: ['CMD', 'redis-cli', 'ping']
            interval: 60s
            timeout: 5s
            retries: 3
            start_period: 40s
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - /etc/timezone:/etc/timezone:ro
            - ./redisdb:/data:rw
        ports:
            - 127.0.0.1:6380:6379
        networks:
            - orientation
        <<: *logging
